# Generated by Django 4.2.30 on 2026-05-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_can_borrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Địa chỉ email này đã tồn tại trong hệ thống.'}, max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
