# Generated by Django 4.2.30 on 2026-05-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('reader', 'Bạn đọc'), ('lecturer', 'Giảng viên'), ('librarian', 'Thủ thư'), ('admin', 'Quản trị viên')], default='reader', max_length=20, verbose_name='Vai trò'),
        ),
    ]
