# Generated by Django 4.2.30 on 2026-05-27 07:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_failed_login_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Số điện thoại không hợp lệ. Phải bắt đầu bằng số 0 và có đúng 10 chữ số.', regex='^0[0-9]{9}$')], verbose_name='Số điện thoại'),
        ),
    ]
