# Generated by Django 4.2.30 on 2026-05-25 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Tên sách đề xuất')),
                ('author_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên tác giả')),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, verbose_name='Mã ISBN')),
                ('reason', models.TextField(verbose_name='Lý do đề xuất')),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối'), ('purchased', 'Đã mua')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú của admin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_proposals', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL, verbose_name='Người đề xuất')),
            ],
            options={
                'verbose_name': 'Đề xuất sách',
                'verbose_name_plural': 'Đề xuất sách',
                'ordering': ['-created_at'],
            },
        ),
    ]
