# Generated by Django 4.2.30 on 2026-06-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookproposal',
            name='isbn',
            field=models.CharField(default='0000000000000', max_length=13, verbose_name='Mã ISBN'),
        ),
    ]
