# Generated by Django 4.2.30 on 2026-05-25 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(max_length=255, verbose_name='Tên Collection trong ChromaDB')),
                ('chunk_count', models.PositiveIntegerField(default=0, verbose_name='Số chunks đã index')),
                ('indexed_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày index')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_index', to='catalog.book', verbose_name='Sách')),
            ],
            options={
                'verbose_name': 'Tài liệu đã Index',
                'verbose_name_plural': 'Tài liệu đã Index',
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Cuộc trò chuyện mới', max_length=255, verbose_name='Tiêu đề')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Phiên chat',
                'verbose_name_plural': 'Phiên chat',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Người dùng'), ('assistant', 'Trợ lý AI')], max_length=10, verbose_name='Vai trò')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('sources', models.JSONField(blank=True, null=True, verbose_name='Nguồn tham khảo (RAG)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession', verbose_name='Phiên chat')),
            ],
            options={
                'verbose_name': 'Tin nhắn',
                'verbose_name_plural': 'Tin nhắn',
                'ordering': ['created_at'],
            },
        ),
    ]
