# Generated by Django 4.2.30 on 2026-05-25 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đặt')),
                ('expires_at', models.DateTimeField(verbose_name='Ngày hết hạn')),
                ('status', models.CharField(choices=[('active', 'Đang đặt'), ('fulfilled', 'Đã hoàn thành'), ('cancelled', 'Đã hủy'), ('expired', 'Đã hết hạn')], default='active', max_length=20, verbose_name='Trạng thái')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='catalog.book', verbose_name='Sách')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Người đặt')),
            ],
            options={
                'verbose_name': 'Đặt trước',
                'verbose_name_plural': 'Đặt trước',
                'ordering': ['-reserved_at'],
            },
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày mượn')),
                ('due_date', models.DateTimeField(verbose_name='Ngày hẹn trả')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='Ngày trả thực tế')),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('approved', 'Đã duyệt'), ('borrowed', 'Đang mượn'), ('returned', 'Đã trả'), ('overdue', 'Quá hạn'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_borrows', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_records', to='catalog.book', verbose_name='Sách')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_records', to=settings.AUTH_USER_MODEL, verbose_name='Người mượn')),
            ],
            options={
                'verbose_name': 'Phiếu mượn',
                'verbose_name_plural': 'Phiếu mượn',
                'ordering': ['-created_at'],
            },
        ),
    ]
