# Generated by Django 4.2.30 on 2026-05-25 21:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='borrow_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày mượn'),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserved_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày đặt'),
        ),
    ]
