# Generated by Django 4.2.30 on 2026-05-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0002_alter_borrowrecord_borrow_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='fine_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Tiền phạt'),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='fine_status',
            field=models.CharField(choices=[('none', 'Không có'), ('unpaid', 'Chưa nộp'), ('paid', 'Đã nộp')], default='none', max_length=20, verbose_name='Trạng thái phạt'),
        ),
    ]
