# Generated by Django 4.2.30 on 2026-05-26 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0003_borrowrecord_fine_amount_borrowrecord_fine_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowrecord',
            name='fine_amount',
        ),
        migrations.RemoveField(
            model_name='borrowrecord',
            name='fine_status',
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('approved', 'Đã duyệt'), ('borrowed', 'Đang mượn'), ('returned', 'Đã trả'), ('overdue', 'Quá hạn'), ('lost', 'Báo mất'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.CreateModel(
            name='FineReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('late_fee', 'Trễ hạn'), ('lost', 'Mất sách'), ('damaged', 'Hỏng sách')], max_length=20, verbose_name='Lý do phạt')),
                ('amount', models.PositiveIntegerField(verbose_name='Số tiền phạt')),
                ('status', models.CharField(choices=[('unpaid', 'Chưa nộp'), ('paid', 'Đã nộp')], default='unpaid', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('borrow_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fine_receipt', to='circulation.borrowrecord', verbose_name='Phiếu mượn')),
            ],
            options={
                'verbose_name': 'Phiếu phạt',
                'verbose_name_plural': 'Phiếu phạt',
                'ordering': ['-created_at'],
            },
        ),
    ]
