# Generated by Django 4.2.30 on 2026-05-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0004_remove_borrowrecord_fine_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='renewal_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Số lần gia hạn'),
        ),
    ]
