# Generated by Django 4.2.30 on 2026-06-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0005_borrowrecord_renewal_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='finereceipt',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Tiền mặt'), ('Transfer', 'Chuyển khoản')], default='Cash', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='notified_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='queue_position',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Notified', 'Notified'), ('Completed', 'Completed'), ('Expired', 'Expired'), ('Cancelled', 'Cancelled')], default='Waiting', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
