# Generated by Django 4.2.30 on 2026-06-27 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0006_finereceipt_payment_method_reservation_notified_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FineReceipt',
        ),
    ]
