# Generated by Django 4.2.30 on 2026-05-25 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên tác giả')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='Tiểu sử')),
            ],
            options={
                'verbose_name': 'Tác giả',
                'verbose_name_plural': 'Tác giả',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Tên thể loại')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Thể loại',
                'verbose_name_plural': 'Thể loại',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Tên NXB')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Địa chỉ')),
            ],
            options={
                'verbose_name': 'Nhà xuất bản',
                'verbose_name_plural': 'Nhà xuất bản',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Tên sách')),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='Mã ISBN')),
                ('publication_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Năm xuất bản')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Ảnh bìa')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='books_pdf/', verbose_name='File PDF')),
                ('total_copies', models.PositiveIntegerField(default=1, verbose_name='Tổng số bản')),
                ('available_copies', models.PositiveIntegerField(default=1, verbose_name='Số bản có sẵn')),
                ('status', models.CharField(choices=[('available', 'Có sẵn'), ('borrowed', 'Đang mượn'), ('reserved', 'Đã đặt trước'), ('maintenance', 'Bảo trì')], default='available', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('authors', models.ManyToManyField(related_name='books', to='catalog.author', verbose_name='Tác giả')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='catalog.category', verbose_name='Thể loại')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='catalog.publisher', verbose_name='Nhà xuất bản')),
            ],
            options={
                'verbose_name': 'Sách',
                'verbose_name_plural': 'Sách',
                'ordering': ['-created_at'],
            },
        ),
    ]
