# Generated by Django 4.2.30 on 2026-05-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.PositiveIntegerField(default=100000, verbose_name='Giá bìa (VNĐ)'),
        ),
    ]
