# Generated by Django 4.2.30 on 2026-06-24 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_book_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to='books_pdf/', verbose_name='File PDF')),
                ('embed_status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Done', 'Done'), ('Failed', 'Failed')], default='Pending', max_length=20, verbose_name='Trạng thái Embed')),
            ],
            options={
                'verbose_name': 'Tài liệu PDF',
                'verbose_name_plural': 'Tài liệu PDF',
            },
        ),
        migrations.RemoveField(
            model_name='book',
            name='pdf_file',
        ),
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_documents', to='catalog.book', verbose_name='Sách'),
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.CharField(default='Unknown', max_length=255, verbose_name='Tác giả'),
            preserve_default=False,
        ),
    ]
